# Generated by Django 5.2.8 on 2025-12-23 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы мышц')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа мышц',
                'verbose_name_plural': 'Группы мышц',
            },
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название упражнения')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('difficulty', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=50, verbose_name='Сложность')),
                ('equipment', models.TextField(blank=True, verbose_name='Необходимое оборудование')),
                ('execution_steps', models.TextField(verbose_name='Шаги выполнения')),
                ('muscle_groups', models.ManyToManyField(to='main.musclegroup', verbose_name='Группы мышц')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='main.tempuser')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес (кг)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Рост (см)')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('total_workouts', models.PositiveIntegerField(default=0, verbose_name='Всего тренировок')),
                ('total_exercises_done', models.PositiveIntegerField(default=0, verbose_name='Всего выполнено упражнений')),
                ('last_workout_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней тренировки')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тренировки')),
                ('is_premade', models.BooleanField(default=False, verbose_name='Готовая тренировка?')),
                ('description', models.TextField(blank=True, verbose_name='Описание тренировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tempuser', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='Количество подходов')),
                ('reps', models.CharField(default='10-12', max_length=50, verbose_name='Количество повторений (например, 10-12)')),
                ('rest_seconds', models.PositiveIntegerField(default=60, verbose_name='Отдых (секунды)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise', verbose_name='Упражнение')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='main.workout')),
            ],
            options={
                'verbose_name': 'Упражнение в тренировке',
                'verbose_name_plural': 'Упражнения в тренировках',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время завершения')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность (минуты)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_history', to='main.tempuser')),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'История тренировок',
                'verbose_name_plural': 'История тренировок',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_exercises', to='main.tempuser')),
            ],
            options={
                'verbose_name': 'Избранное упражнение',
                'verbose_name_plural': 'Избранные упражнения',
                'unique_together': {('user', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('muscle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.musclegroup', verbose_name='Группа мышц')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plan', to='main.tempuser')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'День плана',
                'verbose_name_plural': 'План тренировок',
                'ordering': ['day_of_week'],
                'unique_together': {('user', 'day_of_week')},
            },
        ),
    ]
